import { Metadata } from "next";

export { RootLayout as default } from "@/app/layouts/RootLayout"

export const metadata: Metadata = {
  title: "DOSKA-JES | asd",
  description: "Generated by create next app",
};